/* Mock clinical data — Medion KIS */

const PATIENTS = [
  {
    id: "P-104821",
    name: "Müller, Hannelore",
    geb: "14.03.1948",
    age: 78,
    sex: "w",
    insurance: { type: "GKV", name: "AOK Bayern", number: "A123456789", egk: true },
    station: "INT-3", room: "312", bed: "B",
    admit: "23.04.2026 07:42",
    los: 2,
    primary: "I50.13 — Herzinsuffizienz, NYHA III",
    secondary: ["E11.9 — Diabetes mellitus Typ 2", "I10.90 — Hypertonie"],
    allergies: ["Penicillin (anaphylaktisch)", "Kontrastmittel iod."],
    attending: "Dr. Weber",
    nurse: "Schwester Linda",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Notfall",
    vitals: { hr: 78, sys: 132, dia: 84, spo2: 96, temp: 37.1, rr: 16 },
  },
  {
    id: "P-104822",
    name: "Schmidt, Klaus-Dieter",
    geb: "02.11.1959",
    age: 66,
    sex: "m",
    insurance: { type: "GKV", name: "Techniker Krankenkasse", number: "T998123456", egk: true },
    station: "CHIR-2", room: "207", bed: "A",
    admit: "22.04.2026 14:10",
    los: 3,
    primary: "K35.30 — Akute Appendizitis mit Peritonitis",
    secondary: ["I10.90 — Hypertonie"],
    allergies: ["Keine bekannt"],
    attending: "Dr. Bauer",
    nurse: "Pfleger Tobias",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Notfall — OP",
    vitals: { hr: 82, sys: 128, dia: 78, spo2: 98, temp: 36.9, rr: 14 },
  },
  {
    id: "P-104823",
    name: "Yılmaz, Ayşe",
    geb: "27.07.1972",
    age: 53,
    sex: "w",
    insurance: { type: "GKV", name: "BARMER", number: "B554210019", egk: true },
    station: "ITS", room: "I-04", bed: "—",
    admit: "21.04.2026 22:55",
    los: 4,
    primary: "J96.00 — Akute respiratorische Insuffizienz",
    secondary: ["U07.1 — COVID-19, Virus nachgewiesen", "E66.99 — Adipositas"],
    allergies: ["Latex"],
    attending: "Dr. Hofmann",
    nurse: "Schwester Marta",
    severity: "critical",
    dnr: false,
    aufnahmeart: "Verlegung extern",
    vitals: { hr: 112, sys: 96, dia: 58, spo2: 89, temp: 38.7, rr: 26 },
  },
  {
    id: "P-104824",
    name: "Becker, Liam",
    geb: "08.09.2017",
    age: 8,
    sex: "m",
    insurance: { type: "GKV", name: "DAK-Gesundheit", number: "D201730018", egk: true },
    station: "PÄD", room: "104", bed: "C",
    admit: "24.04.2026 09:15",
    los: 1,
    primary: "S52.5 — Distale Radiusfraktur rechts",
    secondary: [],
    allergies: ["Erdnüsse"],
    attending: "Dr. Köhler",
    nurse: "Schwester Bea",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Elektiv",
    vitals: { hr: 92, sys: 106, dia: 64, spo2: 99, temp: 36.7, rr: 18 },
  },
  {
    id: "P-104825",
    name: "Nowak, Stefan",
    geb: "19.05.1981",
    age: 44,
    sex: "m",
    insurance: { type: "PKV", name: "DKV Premium", number: "PKV-883201", egk: false },
    station: "CHIR-1", room: "118", bed: "A",
    admit: "24.04.2026 06:30",
    los: 1,
    primary: "M23.21 — Meniskusriss medial, Kniegelenk links",
    secondary: [],
    allergies: ["Keine bekannt"],
    attending: "Dr. Bauer",
    nurse: "Pfleger Tobias",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Elektiv — OP heute",
    vitals: { hr: 70, sys: 124, dia: 78, spo2: 99, temp: 36.6, rr: 14 },
  },
  {
    id: "P-104826",
    name: "Fischer, Renate",
    geb: "30.01.1942",
    age: 84,
    sex: "w",
    insurance: { type: "GKV", name: "AOK Plus", number: "A772091833", egk: true },
    station: "INT-3", room: "315", bed: "A",
    admit: "20.04.2026 11:20",
    los: 5,
    primary: "I63.9 — Hirninfarkt, nicht näher bezeichnet",
    secondary: ["I48.0 — Vorhofflimmern", "F03 — Demenz, n.n.b."],
    allergies: ["ASS"],
    attending: "Dr. Weber",
    nurse: "Schwester Linda",
    severity: "watch",
    dnr: true,
    aufnahmeart: "Notfall",
    vitals: { hr: 88, sys: 148, dia: 92, spo2: 95, temp: 37.4, rr: 18 },
  },
  {
    id: "P-104827",
    name: "Krause, Mehmet",
    geb: "12.06.1968",
    age: 57,
    sex: "m",
    insurance: { type: "GKV", name: "AOK Bayern", number: "A331092118", egk: true },
    station: "INT-3", room: "318", bed: "B",
    admit: "23.04.2026 19:05",
    los: 2,
    primary: "K70.30 — Alkoholische Leberzirrhose",
    secondary: ["F10.2 — Alkoholabhängigkeit"],
    allergies: ["Keine bekannt"],
    attending: "Dr. Weber",
    nurse: "Schwester Linda",
    severity: "watch",
    dnr: false,
    aufnahmeart: "Notfall",
    vitals: { hr: 102, sys: 104, dia: 62, spo2: 94, temp: 37.8, rr: 20 },
  },
  {
    id: "P-104828",
    name: "Vogel, Petra",
    geb: "09.10.1989",
    age: 36,
    sex: "w",
    insurance: { type: "GKV", name: "Techniker Krankenkasse", number: "T771820019", egk: true },
    station: "GYN", room: "402", bed: "B",
    admit: "24.04.2026 02:18",
    los: 1,
    primary: "O80 — Spontangeburt eines Einlings",
    secondary: ["Z37.0 — Lebendgeborenes Einling"],
    allergies: ["Keine bekannt"],
    attending: "Dr. Lange",
    nurse: "Hebamme Anja",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Geburt",
    vitals: { hr: 76, sys: 118, dia: 72, spo2: 99, temp: 36.8, rr: 14 },
  },
  {
    id: "P-104829",
    name: "Hartmann, Ingo",
    geb: "21.04.1955",
    age: 71,
    sex: "m",
    insurance: { type: "GKV", name: "BARMER", number: "B118208329", egk: true },
    station: "ITS", room: "I-02", bed: "—",
    admit: "22.04.2026 04:50",
    los: 3,
    primary: "I21.4 — NSTEMI",
    secondary: ["I25.13 — KHK", "E78.0 — Hypercholesterinämie"],
    allergies: ["Keine bekannt"],
    attending: "Dr. Hofmann",
    nurse: "Schwester Marta",
    severity: "watch",
    dnr: false,
    aufnahmeart: "Notfall — Herzkatheter",
    vitals: { hr: 64, sys: 118, dia: 70, spo2: 97, temp: 36.8, rr: 16 },
  },
  {
    id: "P-104830",
    name: "Roth, Sabine",
    geb: "05.12.1976",
    age: 49,
    sex: "w",
    insurance: { type: "GKV", name: "DAK-Gesundheit", number: "D661920401", egk: true },
    station: "CHIR-2", room: "211", bed: "A",
    admit: "24.04.2026 08:40",
    los: 1,
    primary: "K80.20 — Cholezystolithiasis",
    secondary: [],
    allergies: ["Morphin"],
    attending: "Dr. Bauer",
    nurse: "Pfleger Tobias",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Elektiv — OP heute",
    vitals: { hr: 74, sys: 126, dia: 80, spo2: 98, temp: 36.7, rr: 14 },
  },
  {
    id: "P-104831",
    name: "Kaiser, Otto",
    geb: "11.02.1939",
    age: 87,
    sex: "m",
    insurance: { type: "GKV", name: "AOK Plus", number: "A992101188", egk: true },
    station: "INT-3", room: "320", bed: "A",
    admit: "19.04.2026 23:10",
    los: 6,
    primary: "J18.9 — Pneumonie, n.n.b.",
    secondary: ["F03 — Demenz", "Z74.1 — Hilfsbedürftigkeit Pflege"],
    allergies: ["Penicillin"],
    attending: "Dr. Weber",
    nurse: "Schwester Linda",
    severity: "stable",
    dnr: true,
    aufnahmeart: "Notfall",
    vitals: { hr: 84, sys: 122, dia: 76, spo2: 96, temp: 37.5, rr: 18 },
  },
  {
    id: "P-104832",
    name: "Schneider, Anna",
    geb: "23.08.1995",
    age: 30,
    sex: "w",
    insurance: { type: "GKV", name: "Techniker Krankenkasse", number: "T420118229", egk: true },
    station: "GYN", room: "405", bed: "A",
    admit: "23.04.2026 17:30",
    los: 2,
    primary: "N80.9 — Endometriose",
    secondary: [],
    allergies: ["Keine bekannt"],
    attending: "Dr. Lange",
    nurse: "Hebamme Anja",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Elektiv",
    vitals: { hr: 72, sys: 116, dia: 70, spo2: 99, temp: 36.6, rr: 14 },
  },
  // ── Amnesie-Patienten ────────────────────────────────────────────────────
  {
    id: "P-104833",
    name: "Baumann, Ernst",
    geb: "14.11.1957",
    age: 68,
    sex: "m",
    insurance: { type: "GKV", name: "AOK Bayern", number: "A881920174", egk: true },
    station: "NEU", room: "501", bed: "B",
    admit: "25.04.2026 16:40",
    los: 1,
    primary: "R41.3 — Transiente globale Amnesie (TGA)",
    secondary: ["I10.90 — Arterielle Hypertonie"],
    allergies: ["Keine bekannt"],
    attending: "Dr. Richter",
    nurse: "Pfleger Jonas",
    severity: "watch",
    dnr: false,
    aufnahmeart: "Notfall",
    vitals: { hr: 72, sys: 136, dia: 82, spo2: 99, temp: 36.6, rr: 14 },
    anamnese: {
      vorerkrankungen: ["Arterielle Hypertonie seit 10 J.", "Keine Epilepsie, kein Schlaganfall"],
      medikamente: ["Ramipril 5mg 1-0-0", "HCT 12,5mg 1-0-0"],
      sozial: "Rentner, verheiratet, lebt selbstständig. Ex-Raucher (15 py, sistiert vor 8 J.).",
      auslöser: "Intensives körperliches Training (Laufen, 10 km) heute Morgen.",
      verlauf: "Plötzlicher Beginn gegen 14:00 Uhr. Wiederholtes Stellen identischer Fragen über ca. 4-5 Stunden. Keine Bewusstlosigkeit, kein Sturz, keine Zungenbisse, kein Erbrechen. Jetzt vollständig erholt, aber lückenhafte Erinnerung an Ereignis.",
      famAnamnese: "Vater: Herzinfarkt mit 72 J. Keine Epilepsie in Familie.",
    },
  },
  {
    id: "P-104834",
    name: "Vogel, Karl-Heinz",
    geb: "03.07.1963",
    age: 62,
    sex: "m",
    insurance: { type: "GKV", name: "DAK-Gesundheit", number: "D882031174", egk: true },
    station: "NEU", room: "504", bed: "A",
    admit: "22.04.2026 09:15",
    los: 4,
    primary: "F10.6 — Alkohol-bedingtes Korsakoff-Syndrom",
    secondary: ["K70.30 — Alkoholische Leberzirrhose Child A", "E51.2 — Wernicke-Enzephalopathie (Anamnese)"],
    allergies: ["Keine bekannt"],
    attending: "Dr. Richter",
    nurse: "Pfleger Jonas",
    severity: "watch",
    dnr: false,
    aufnahmeart: "Verlegung Psychiatrie",
    vitals: { hr: 84, sys: 128, dia: 78, spo2: 97, temp: 36.9, rr: 16 },
    anamnese: {
      vorerkrankungen: [
        "Chronischer Alkoholabusus >25 J. (>100g/d)",
        "Wernicke-Enzephalopathie-Episode 2023 (Klinik Süd)",
        "Alkoholische Leberzirrhose Child A (diagnostiziert 2024)",
        "Z.n. stationärer Entgiftung 3× (zuletzt Akutpsychiatrie)",
      ],
      medikamente: ["Thiamin 300mg i.v. (aktuell)", "Folsäure 5mg 1-0-0", "Lactulose 3×15ml"],
      sozial: "Frührentner. Lebt alleine. Tochter in München (Hauptansprechpartnerin). Führerschein bereits entzogen (DUI 2022). Betreuer: Frau Richter, Betreuungsgericht München.",
      verlauf: "Nach stationärer Entgiftung persistierende schwere Gedächtnisstörungen: anterograde Amnesie (kann neue Inhalte nicht behalten), retrograde Amnesie für die letzten ~18 Monate, ausgeprägte Konfabulationen. MRT: Korsakoff-typische Veränderungen Corpora mammillaria + Thalami bds.",
      famAnamnese: "Mutter: Alkoholabhängigkeit. Keine sonstigen neurolog. Erkrankungen bekannt.",
    },
  },
];

// OR / OP-Plan
const OP_ROOMS = ["OP-1", "OP-2", "OP-3", "OP-4 (Notfall)"];
const OP_PROCEDURES = [
  { id: "OP-2401", room: "OP-1", patient: "P-104825", patientName: "Nowak, S.", procedure: "Arthroskopie Knie li. — Meniskusresektion", surgeon: "Dr. Bauer", anaesthetist: "Dr. Schulz", start: "08:00", end: "09:30", status: "completed", priority: "elektiv" },
  { id: "OP-2402", room: "OP-1", patient: "P-104830", patientName: "Roth, S.", procedure: "Lap. Cholezystektomie", surgeon: "Dr. Bauer", anaesthetist: "Dr. Schulz", start: "10:00", end: "11:45", status: "in-progress", priority: "elektiv" },
  { id: "OP-2403", room: "OP-1", patient: "P-104840", patientName: "Wagner, M.", procedure: "Hernia inguinalis re., TEP", surgeon: "Dr. Bauer", anaesthetist: "Dr. Schulz", start: "12:30", end: "13:45", status: "scheduled", priority: "elektiv" },
  { id: "OP-2404", room: "OP-1", patient: "P-104841", patientName: "Decker, R.", procedure: "Strumaresektion subtotal", surgeon: "Dr. Bauer", anaesthetist: "Dr. Schulz", start: "14:30", end: "16:30", status: "scheduled", priority: "elektiv" },

  { id: "OP-2410", room: "OP-2", patient: "P-104842", patientName: "Brandt, U.", procedure: "Hüft-TEP rechts", surgeon: "Dr. Engel", anaesthetist: "Dr. Pohl", start: "07:30", end: "10:30", status: "completed", priority: "elektiv" },
  { id: "OP-2411", room: "OP-2", patient: "P-104843", patientName: "Lehmann, F.", procedure: "Knie-TEP links", surgeon: "Dr. Engel", anaesthetist: "Dr. Pohl", start: "11:00", end: "13:30", status: "in-progress", priority: "elektiv" },
  { id: "OP-2412", room: "OP-2", patient: "P-104844", patientName: "Hess, T.", procedure: "Schulterarthroskopie", surgeon: "Dr. Engel", anaesthetist: "Dr. Pohl", start: "14:30", end: "16:00", status: "scheduled", priority: "elektiv" },

  { id: "OP-2420", room: "OP-3", patient: "P-104845", patientName: "Klein, P.", procedure: "Sectio caesarea", surgeon: "Dr. Lange", anaesthetist: "Dr. Pohl", start: "09:00", end: "10:00", status: "completed", priority: "elektiv" },
  { id: "OP-2421", room: "OP-3", patient: "P-104846", patientName: "Otto, B.", procedure: "Hysterektomie laparoskopisch", surgeon: "Dr. Lange", anaesthetist: "Dr. Mayer", start: "11:00", end: "13:30", status: "scheduled", priority: "elektiv" },
  { id: "OP-2422", room: "OP-3", patient: "P-104847", patientName: "Reinhardt, K.", procedure: "Konisation", surgeon: "Dr. Lange", anaesthetist: "Dr. Mayer", start: "14:30", end: "15:15", status: "scheduled", priority: "elektiv" },

  { id: "OP-2430", room: "OP-4 (Notfall)", patient: "P-104822", patientName: "Schmidt, K.-D.", procedure: "Appendektomie laparoskopisch", surgeon: "Dr. Bauer", anaesthetist: "Dr. Schulz", start: "01:15", end: "02:30", status: "completed", priority: "notfall" },
  { id: "OP-2431", room: "OP-4 (Notfall)", patient: "P-104848", patientName: "Köhler, J.", procedure: "Re-Laparotomie — Nachblutung", surgeon: "Dr. Engel", anaesthetist: "Dr. Pohl", start: "13:00", end: "—", status: "scheduled", priority: "notfall" },
];

// ICU vitals over time (sparkline data)
const ICU_VITALS = {
  "P-104823": {
    hr:   [108, 112, 110, 115, 118, 114, 112, 110, 108, 112, 116, 112],
    sys:  [102, 100,  98,  96,  94,  96,  98,  96,  94,  92,  94,  96],
    spo2: [ 92,  91,  90,  89,  88,  87,  88,  89,  88,  88,  89,  89],
    rr:   [ 22,  24,  26,  28,  26,  24,  26,  26,  28,  26,  26,  26],
  },
  "P-104829": {
    hr:   [ 60,  62,  64,  66,  64,  62,  60,  62,  64,  66,  64,  64],
    sys:  [120, 122, 118, 116, 118, 120, 122, 118, 116, 118, 120, 118],
    spo2: [ 98,  98,  97,  97,  98,  98,  97,  97,  98,  97,  97,  97],
    rr:   [ 14,  16,  16,  18,  16,  16,  14,  16,  16,  18,  16,  16],
  },
  "P-104852": {
    hr:   [ 96,  98,  94,  92,  94,  96,  98,  96,  94,  96,  98,  96],
    sys:  [108, 110, 112, 110, 108, 106, 108, 110, 112, 108, 110, 108],
    spo2: [ 94,  93,  94,  95,  94,  93,  94,  94,  93,  94,  94,  94],
    rr:   [ 20,  22,  20,  18,  20,  22,  20,  20,  22,  20,  20,  20],
  },
};

const ICU_PATIENTS_EXTRA = [
  {
    id: "P-104852",
    name: "Albrecht, Werner",
    geb: "06.07.1953",
    age: 72,
    sex: "m",
    station: "ITS", room: "I-06", bed: "—",
    primary: "T82.7 — Sepsis nach Klappenersatz",
    severity: "watch",
    vitals: { hr: 96, sys: 108, dia: 64, spo2: 94, temp: 38.2, rr: 20 },
    ventilator: { mode: "PSV", peep: 8, fio2: 0.45, vt: 480, rr: 18 },
    sedation: "RASS -1",
    drugs: ["Noradrenalin 0.08 µg/kg/min", "Propofol 200 mg/h", "Meropenem 1 g 8h"],
    catheters: ["ZVK", "Arterie", "DK", "ZVD"],
  },
];

const MEDICATION = [
  // For Müller, Hannelore (P-104821)
  { patient: "P-104821", name: "Bisoprolol 5 mg", form: "Tabl.", route: "p.o.", schedule: "1-0-0", times: ["08:00"], from: "23.04.", until: "—", indication: "Herzinsuffizienz", interaction: false, aut: false, status: "ok" },
  { patient: "P-104821", name: "Ramipril 5 mg", form: "Tabl.", route: "p.o.", schedule: "1-0-1", times: ["08:00", "20:00"], from: "23.04.", until: "—", indication: "Hypertonie / HI", interaction: false, aut: false, status: "ok" },
  { patient: "P-104821", name: "Furosemid 40 mg", form: "Tabl.", route: "p.o.", schedule: "1-0-0", times: ["08:00"], from: "23.04.", until: "—", indication: "Volumenüberladung", interaction: false, aut: false, status: "ok" },
  { patient: "P-104821", name: "Metformin 1000 mg", form: "Tabl.", route: "p.o.", schedule: "1-0-1", times: ["08:00", "20:00"], from: "23.04.", until: "—", indication: "DM Typ 2", interaction: false, aut: true, status: "ok" },
  { patient: "P-104821", name: "Atorvastatin 40 mg", form: "Tabl.", route: "p.o.", schedule: "0-0-1", times: ["20:00"], from: "23.04.", until: "—", indication: "Lipidsenkung", interaction: false, aut: true, status: "ok" },
  { patient: "P-104821", name: "Apixaban 5 mg", form: "Tabl.", route: "p.o.", schedule: "1-0-1", times: ["08:00", "20:00"], from: "23.04.", until: "—", indication: "Antikoagulation", interaction: true, aut: false, status: "warn", warning: "Wechselwirkung mit Amiodaron — INR überwachen" },
  { patient: "P-104821", name: "Pantoprazol 40 mg", form: "Tabl.", route: "p.o.", schedule: "1-0-0", times: ["08:00"], from: "23.04.", until: "—", indication: "Magenschutz", interaction: false, aut: false, status: "ok" },
];

const LAB_RESULTS = [
  { patient: "P-104821", date: "24.04. 06:14", panel: "Klinische Chemie", values: [
    { name: "Kreatinin", v: "1.42", unit: "mg/dl", ref: "0.5–1.1", flag: "high" },
    { name: "Harnstoff", v: "62", unit: "mg/dl", ref: "10–50", flag: "high" },
    { name: "GFR (CKD-EPI)", v: "44", unit: "ml/min", ref: ">60", flag: "low" },
    { name: "Natrium", v: "138", unit: "mmol/l", ref: "135–145", flag: "ok" },
    { name: "Kalium", v: "4.2", unit: "mmol/l", ref: "3.5–5.0", flag: "ok" },
    { name: "NT-proBNP", v: "3 240", unit: "pg/ml", ref: "<300", flag: "high" },
    { name: "Troponin T hs", v: "18", unit: "ng/l", ref: "<14", flag: "high" },
    { name: "CRP", v: "8.4", unit: "mg/l", ref: "<5", flag: "high" },
  ]},
  { patient: "P-104821", date: "24.04. 06:14", panel: "Hämatologie", values: [
    { name: "Hb", v: "11.2", unit: "g/dl", ref: "12.0–16.0", flag: "low" },
    { name: "Leukozyten", v: "8.4", unit: "/nl", ref: "4.0–10.0", flag: "ok" },
    { name: "Thrombozyten", v: "212", unit: "/nl", ref: "150–400", flag: "ok" },
  ]},
];

// Stations / wards
const STATIONS = [
  { code: "INT-3", name: "Innere Medizin 3 — Kardiologie", beds: 28, occupied: 24, free: 4, isolation: 1, lead: "Dr. Weber", floor: "3. OG" },
  { code: "INT-4", name: "Innere Medizin 4 — Pneumologie", beds: 24, occupied: 22, free: 2, isolation: 3, lead: "Dr. Sommer", floor: "3. OG" },
  { code: "CHIR-1", name: "Allgemein- & Viszeralchirurgie", beds: 30, occupied: 26, free: 4, isolation: 0, lead: "Dr. Bauer", floor: "2. OG" },
  { code: "CHIR-2", name: "Unfallchirurgie & Orthopädie", beds: 26, occupied: 23, free: 3, isolation: 0, lead: "Dr. Engel", floor: "2. OG" },
  { code: "ITS", name: "Intensivstation", beds: 12, occupied: 10, free: 2, isolation: 4, lead: "Dr. Hofmann", floor: "1. OG" },
  { code: "GYN", name: "Gynäkologie & Geburtshilfe", beds: 22, occupied: 18, free: 4, isolation: 0, lead: "Dr. Lange", floor: "4. OG" },
  { code: "PÄD", name: "Pädiatrie", beds: 20, occupied: 14, free: 6, isolation: 1, lead: "Dr. Köhler", floor: "4. OG" },
  { code: "NEU", name: "Neurologie / Stroke Unit", beds: 18, occupied: 16, free: 2, isolation: 0, lead: "Dr. Richter", floor: "5. OG" },
];

// Imaging studies
const IMAGING = [
  { id: "S-44021", patient: "P-104821", date: "24.04.2026 07:55", modality: "Rö-Thorax", region: "Thorax pa/lateral", status: "befundet", radiologist: "Dr. Wolff", indication: "Dyspnoe, V.a. kardiale Stauung", findings: "Vergrößertes Herz (CTR 0.62), interstitielle Stauungszeichen, beidseits basal kleine Pleuraergüsse. Keine pneumonische Infiltration." },
  { id: "S-44022", patient: "P-104826", date: "20.04.2026 12:45", modality: "MRT", region: "Schädel nativ + KM", status: "befundet", radiologist: "Dr. Wolff", indication: "V.a. Hirninfarkt", findings: "Frischer ischämischer Infarkt im Mediastromgebiet rechts (DWI+, ADC↓). Keine Blutung." },
  { id: "S-44023", patient: "P-104823", date: "23.04.2026 02:30", modality: "CT", region: "Thorax + KM", status: "befundet", radiologist: "Dr. Bach", indication: "ARDS, V.a. Lungenembolie", findings: "Ausgedehnte beidseitige Milchglas-Trübungen, betont posterior. Keine zentrale Lungenembolie. Pleuraergüsse rechts > links." },
  { id: "S-44024", patient: "P-104822", date: "22.04.2026 13:20", modality: "Sonographie", region: "Abdomen", status: "befundet", radiologist: "Dr. Bach", indication: "RUQ-Schmerz, V.a. Appendizitis", findings: "Wandverdickte, nicht komprimierbare Appendix, Durchmesser 11 mm. Freie Flüssigkeit periappendikulär." },
  { id: "S-44025", patient: "P-104829", date: "22.04.2026 06:10", modality: "Koro", region: "Linksherzkatheter", status: "befundet", radiologist: "Dr. Wolff", indication: "NSTEMI", findings: "Hochgradige Stenose RIVA prox. (90%). PCI mit DES erfolgreich. RCA und RCX o.B." },
];

// Today's appointments / agenda
const AGENDA = [
  { time: "07:30", title: "Morgenvisite Station INT-3", duration: "60 min", type: "visite", location: "Station 3", attendees: 4 },
  { time: "09:00", title: "Tumorboard — Wöchentlich", duration: "45 min", type: "konferenz", location: "Konferenzraum B", attendees: 12 },
  { time: "10:00", title: "Aufklärung OP — Frau Roth", duration: "20 min", type: "aufklärung", location: "Zimmer 211", attendees: 1, patient: "Roth, Sabine" },
  { time: "10:30", title: "Sprechstunde — Müller, Hannelore", duration: "15 min", type: "termin", location: "Zimmer 312", attendees: 1, patient: "Müller, Hannelore" },
  { time: "11:00", title: "Konsil Neurologie — Hr. Krause", duration: "30 min", type: "konsil", location: "INT-3", attendees: 2, patient: "Krause, Mehmet" },
  { time: "13:00", title: "Mittagsbesprechung", duration: "30 min", type: "team", location: "Arztzimmer", attendees: 8 },
  { time: "14:30", title: "Entlassgespräch — Hr. Becker", duration: "20 min", type: "entlassung", location: "PÄD 104", attendees: 2, patient: "Becker, Liam" },
  { time: "16:00", title: "Abendvisite", duration: "45 min", type: "visite", location: "Station 3", attendees: 3 },
];

// Tasks / inbox
const TASKS = [
  { id: 1, prio: "high", text: "Befund freigeben: CT-Thorax — Yılmaz, A.", from: "Dr. Bach", time: "vor 12 Min.", type: "befund" },
  { id: 2, prio: "high", text: "Rückruf Angehörige Frau Fischer", from: "Stationssekretariat", time: "vor 38 Min.", type: "telefonat" },
  { id: 3, prio: "med", text: "eAU verlängern — Hr. Krause", from: "MFA Stark", time: "vor 1 Std.", type: "eau" },
  { id: 4, prio: "med", text: "Antrag AHB — Frau Müller", from: "Sozialdienst", time: "vor 1 Std.", type: "antrag" },
  { id: 5, prio: "med", text: "Konsil Kardiologie offen — Hr. Hartmann", from: "Dr. Sommer", time: "vor 2 Std.", type: "konsil" },
  { id: 6, prio: "low", text: "Arztbrief gegenzeichnen — 4 Briefe", from: "System", time: "vor 3 Std.", type: "brief" },
  { id: 7, prio: "low", text: "Pflegeüberleitung Hr. Kaiser", from: "Pflege INT-3", time: "vor 4 Std.", type: "ueberleitung" },
];

const REFERRALS = [
  { id: "Ü-2026-0241", date: "23.04.2026", patient: "Müller, Hannelore", to: "Kardiologie ambulant — Praxis Dr. Berger", reason: "TTE, Verlaufskontrolle Herzinsuffizienz", urgency: "regulär", status: "versendet" },
  { id: "Ü-2026-0242", date: "23.04.2026", patient: "Krause, Mehmet", to: "Suchtmedizin — MVZ Süd", reason: "Anschlussbehandlung Alkoholentzug", urgency: "regulär", status: "Entwurf" },
  { id: "Ü-2026-0243", date: "24.04.2026", patient: "Becker, Liam", to: "Physiotherapie — Praxis Lehner", reason: "Mobilisation nach Radiusfraktur", urgency: "regulär", status: "versendet" },
  { id: "Ü-2026-0244", date: "24.04.2026", patient: "Fischer, Renate", to: "Geriatrische Reha — Klinik Sonnenhof", reason: "AHB nach Hirninfarkt", urgency: "hoch", status: "in Bearbeitung" },
];

// SOAP / Verlaufsdokumentation — matches backend data/patients/soap_history.jsonl
const SOAP_HISTORY = [
  // ── Müller, Hannelore (P-104821) ──────────────────────────────────────────
  {
    id: "SH-001", patient: "P-104821", date: "23.04.2026", time: "12:30", author: "Dr. Weber",
    type: "Aufnahme",
    S: "Patientin, 78 J., stellt sich mit progredienter Belastungsdyspnoe seit 4 Tagen vor. Orthopnoe mit 2 Kissen, Gewichtszunahme +2,8 kg in 7 Tagen, Unterschenkelödeme beidseits zunehmend.",
    O: "RR 158/96 mmHg, HF 96/min (unregelmäßig), SpO₂ 92% RA. Stauungszeichen: JVD+, feinblasige RGs basal bds., S3-Galopp. UEX: prätibiale Ödeme ++. EKG: VHF 96/min. Rö-Thorax: Herzverbreiterung, Kerley-B-Linien, Pleuraergüsse bds.",
    A: "Dekompensierte Herzinsuffizienz NYHA III (I50.13) bei DCM (I42.0). VHF (I48.0) bekannt. Niereninsuffizienz Grad 3a (N18.31) — DD prärenale Komponente. DM Typ 2 (E11.9) und aHT (I10.90) stabil.",
    P: "Furosemid 80mg i.v. Bolus, dann 40mg p.o. 2×/d. Bilanzierung Ziel -500ml/24h. Bettruhe, O₂ bei SpO₂<94%. Krea + Elektrolyte 6-stündlich. Echo morgen. Antikoagulation: Apixaban weiter. Konsil Kardiologie angemeldet.",
  },
  {
    id: "SH-002", patient: "P-104821", date: "24.04.2026", time: "08:15", author: "Dr. Weber",
    type: "Verlauf",
    S: "Leichte Besserung der Dyspnoe. Schläft mit 1 Kissen. Ödeme subjektiv rückläufig. Urinausscheidung laut Bilanz: +680 ml Negativbilanz gestern.",
    O: "RR 132/84 mmHg, HF 78/min, SpO₂ 96% RA. RGs basal deutlich abnehmend. UEX: prätibiale Ödeme +/+ (rückläufig). Gewicht -1,4 kg. Krea 1,42 mg/dl ↑ (prärenal?), K+ 4,2, NT-proBNP 3240 pg/ml. Echo: EF 35%, globale Hypokinesie.",
    A: "Klinisch deutlich gebesserte HI unter Diuretikatherapie. Kreatininanstieg unter Furosemid — DD prärenal. Troponin-T 18 ng/l grenzwertig, kein NSTEMI-Muster.",
    P: "Furosemid auf 40mg 1×/d reduzieren. Krea + E'lyte morgen. TTE ambulant in 6 Wo. Sozialdienst: AHB-Antrag initiiert. Patientenedukation Gewichtsprotokoll. Entlassung voraussichtlich 26.04.",
  },
  // ── Fischer, Renate — Amnesie nach Hirninfarkt (P-104826) ─────────────────
  {
    id: "SH-010", patient: "P-104826", date: "20.04.2026", time: "13:45", author: "Dr. Weber",
    type: "Aufnahme",
    S: "Patientin, 84 J., aus Seniorenheim eingeliefert nach Sturz + Bewusstseinsstörung ca. 5 Min. Gesichtsschiefe li. beobachtet. Sprachstörung. Seit Vortag zunehmend verwirrt. Vorbekannt: VHF (Apixaban), Demenz F03 (Stufe 1-2).",
    O: "RR 172/98 mmHg, HF 88/min (arrhythmisch), SpO₂ 95%. Neurologisch: Bewusstsein getrübt (GCS E3V4M6), ausgeprägte anterograde + retrograde Amnesie. NIHSS 4. MRT: frischer ischämischer Infarkt Mediastromgebiet rechts (DWI+, ADC↓). Keine Blutung.",
    A: "Frischer zerebraler Infarkt (I63.9) im rechten Mediastromgebiet, vermutlich kardioembolisch bei VHF (I48.0). Schwere Amnesie als Leitsymptom. Vorschaden durch Demenz (F03). DNR-Wunsch in Patientenverfügung.",
    P: "Lyse-KI (Zeitfenster, Demenz). Apixaban weiter (ASS als KI). RR-Ziel 140-160. Neurolog. Monitoring. Schluckscreening. Physio + Ergo Konsil. Palliativmedizin-Konsil. Angehörigengespräch heute 14:00. Geriatrische Reha vorbereiten.",
  },
  {
    id: "SH-011", patient: "P-104826", date: "22.04.2026", time: "09:00", author: "Dr. Weber",
    type: "Verlauf",
    S: "Patientin erkennt Tochter heute, nennt Namen korrekt. Fragt wiederholt: 'Wann gehe ich nach Hause?' — keine Erinnerung an Vortag. Schlucken gebessert, nimmt breiige Kost. Keine Schmerzen.",
    O: "RR 148/88 mmHg. Neurologisch: MMSE 12/30 (vs. 18/30 vor 3 Mo., Heim-Dokumentation). Orientierung zu Person erhalten, zu Zeit + Ort stark eingeschränkt. Keine neue Hemiparese. Schluck: sicher bei Brei.",
    A: "Subakuter Verlauf nach Infarkt. Amnesie partiell rückläufig für Ferngedächtnis, Kurzzeitgedächtnis weiterhin schwer beeinträchtigt. Prognose für vollständige Erholung ungünstig bei Demenz-Vorschaden.",
    P: "Apixaban fortführen. Physio täglich. Neuropsychologie-Konsil angemeldet. Angehörigengespräch: Ziel geriatrische Reha besprochen + akzeptiert. AHB-Antrag Klinik Sonnenhof eingereicht.",
  },
  // ── Baumann, Ernst — TGA (P-104833) ──────────────────────────────────────
  {
    id: "SH-020", patient: "P-104833", date: "25.04.2026", time: "17:20", author: "Dr. Richter",
    type: "Aufnahme",
    S: "Patient, 68 J., wird von Ehefrau vorgestellt. Plötzlicher Beginn gegen 14:00 Uhr: repetitive Fragen ('Was machen wir heute?', 'Wo sind wir?') über ca. 4-5 Stunden ohne Memoration der Antworten. Jetzt vollständig erholt, komplette Amnesie für den Zeitraum. Auslöser: körperliche Belastung (10 km Lauf). Kein Trauma, keine Hemiparese, kein Erbrechen, kein Zungenbiss.",
    O: "Vollständig orientiert. MMSE 29/30. Anterograde Amnesie für 4-5 h (der Vorfall selbst). Keine fokal-neurol. Zeichen. MRT (DWI): kein Infarkt. EEG: unauffällig. CK 280 U/l (nach Sport, erwartet). Troponin negativ.",
    A: "Transiente globale Amnesie (TGA) (R41.3) — klassisches Bild. Ausschluss TIA (MRT neg.) und epileptischer Anfall (EEG neg.). Rezidivrisiko 5-8% jährlich. Exzellente Prognose.",
    P: "Stationäre Beobachtung 24h. Keine spezifische Therapie. Patientenedukation: gutartige Prognose, >95% Vollrestitution. Körperliche Extrembelastung 4 Wochen meiden. Neurol. Ambulanz in 6 Wochen. Fahreignung: temporär einschränken bis Follow-up.",
  },
  // ── Vogel, Karl-Heinz — Korsakoff-Syndrom (P-104834) ─────────────────────
  {
    id: "SH-030", patient: "P-104834", date: "22.04.2026", time: "10:30", author: "Dr. Richter",
    type: "Aufnahme",
    S: "Patient, 62 J., Verlegung aus Akutpsychiatrie nach Entgiftung. Chronischer Alkoholabusus >25 J. (>100g/d). Nach Entgiftung: persistierende schwere Gedächtnisstörungen. Anterograde Amnesie (kann keine neuen Informationen speichern). Retrograde Amnesie letzte ~18 Monate. Ausgeprägte Konfabulationen. Vorbekannte Wernicke-Enzephalopathie-Episode 2023.",
    O: "Wach, kooperativ, orientiert zu Person, desorientiert zu Zeit + Ort. MMSE 18/30. 3-Wörter-Test nach 5 Min.: 0/3. Konfabulation: erzählt überzeugend von 'gestriger Reise nach Hamburg'. MRT: T2-Hyperintensitäten Corpora mammillaria + Thalami bds. — Korsakoff-Muster.",
    A: "Alkoholisches Korsakoff-Syndrom (F10.6) auf Boden Wernicke-Enzephalopathie. Schwere anterograde + retrograde Amnesie + Konfabulation. Prognose: ~25% Teilbesserung bei Abstinenz, selten Vollrestitution.",
    P: "Thiamin 300mg i.v. 1×/d × 5 Tage, dann p.o. dauerhaft. Absolute Abstinenz. Neuropsychol. Diagnostik + Reha. Heimplatz-Anfrage initiiert (alleinstehend, nicht mehr selbstständig). Angehörige informiert. Verlaufskontrolle MRT in 3 Monaten.",
  },
  // ── Krause, Mehmet — Leberzirrhose / Entzug (P-104827) ──────────────────
  {
    id: "SH-040", patient: "P-104827", date: "23.04.2026", time: "21:00", author: "Dr. Weber",
    type: "Aufnahme",
    S: "Patient, 57 J., Alkoholabusus >30 J. (0,7-1,0 L Schnaps/d). Jetzt: Oberbauchschmerzen re., Übelkeit/Erbrechen, Ikterus. Letzter Alkohol gestern Abend. Entzugszeichen: Tremor ++, Schwitzen, innere Unruhe.",
    O: "RR 138/88 mmHg, HF 108/min, Temp 37,8°C, SpO₂ 94%. Sklerenikterus ++. Abdomen: gespannt, Druckschmerz re. OB, Hepatomegalie 4 QF. CIWA-Ar: 14. Labor: Bili 4,8 mg/dl, GGT 382 U/l, AST 156, INR 1,7. Sono: Leberparenchymveränderungen, Aszites gering.",
    A: "Akut-auf-chron. Leberversagen (K72.00) bei alkohol. Leberzirrhose (K70.30) Child-Pugh B. Alkohol-Entzugssyndrom CIWA 14 (F10.231).",
    P: "Diazepam nach CIWA-Ar-Schema. Thiamin 300mg i.v. 1×/d. Multivitamine. Propranolol 40mg 2×/d. Lactulose 3×15ml. Sono-Kontrolle 48h. Suchtmedizin-Konsil morgen. Entlassung nach Entgiftung → MVZ Süd.",
  },
  // ── Hartmann, Ingo — NSTEMI post-PCI (P-104829) ──────────────────────────
  {
    id: "SH-050", patient: "P-104829", date: "22.04.2026", time: "07:30", author: "Dr. Hofmann",
    type: "Aufnahme",
    S: "Patient, 71 J., wacht 04:30 mit retrosternalen Druckschmerzen auf, Ausstrahlung li. Arm + Kiefer, Kaltschweißigkeit, Übelkeit. Bekannte KHK (Stent LAD 2019), aHT, Hypercholesterinämie. Aktuelle Medikation: ASS 100, Bisoprolol 5mg, Atorvastatin 40mg.",
    O: "RR 148/92 mmHg, HF 84/min, SpO₂ 97%. EKG: ST-Hebungen V1-V3. Troponin T hs 1840 ng/l (Norm <14). LHK sofort: RIVA prox. 90% De-novo-Stenose. PCI mit DES (Xience 3.5×24mm) erfolgreich, TIMI-3-Fluss. Echo: EF 48%, anteriore Hypokinesie.",
    A: "STEMI Vorderwand (I21.4) bei KHK-Progression. Erfolgreiche Primär-PCI. Dual-Plättchenhemmung initiiert.",
    P: "Ticagrelor 180mg Loading → 90mg 2×/d × 12 Monate. ASS 100mg dauerhaft. Atorvastatin auf 80mg hochdosiert. Betablocker weiter. Heparin i.v. bis morgen. ITS-Monitoring 48h. Kardiolog. Reha anmelden. Rauchstopp-Beratung.",
  },
];

// Neuropsychology / cognitive test results
const NEURO_PSYCH = [
  {
    patient: "P-104826", date: "22.04.2026", examiner: "Dr. Neuner (Neuropsychologie)",
    tests: [
      { name: "MMSE", score: "12/30", norm: "≥24 unauffällig", interpretation: "Schwere kognitive Einschränkung" },
      { name: "Uhrentest", score: "2/6", norm: "5-6 unauffällig", interpretation: "Planung + Exekutivfunktion gestört" },
      { name: "Wortliste (3 Wörter nach 5 Min)", score: "0/3", norm: "3/3", interpretation: "Schwere Neugedächtnissstörung" },
    ],
    conclusion: "Ausgeprägte anterograde Amnesie und Orientierungsstörung. Deutliche Verschlechterung zu Vorbefund (MMSE 18/30, Nov. 2025). Vereinbar mit Infarktfolge überlagert auf vorbestehende Demenz.",
  },
  {
    patient: "P-104833", date: "25.04.2026", examiner: "Dr. Richter (Neurologie)",
    tests: [
      { name: "MMSE", score: "29/30", norm: "≥24 unauffällig", interpretation: "Unauffällig" },
      { name: "Wortliste (3 Wörter nach 5 Min)", score: "3/3", norm: "3/3", interpretation: "Normal" },
      { name: "Orientierung (Zeit, Ort, Person)", score: "10/10", norm: "10/10", interpretation: "Vollständig orientiert" },
    ],
    conclusion: "Vollständige kognitive Erholung nach TGA-Episode. Amnesie auf Vorfall selbst beschränkt (normale retrograde + anterograde Funktion jetzt).",
  },
  {
    patient: "P-104834", date: "23.04.2026", examiner: "Dr. Neuner (Neuropsychologie)",
    tests: [
      { name: "MMSE", score: "18/30", norm: "≥24 unauffällig", interpretation: "Moderate Einschränkung" },
      { name: "Wortliste (3 Wörter nach 5 Min)", score: "0/3", norm: "3/3", interpretation: "Schwere anterograde Amnesie" },
      { name: "Rivermead Behavioural Memory Test", score: "4/24", norm: "≥17", interpretation: "Schwere Alltagsgedächtnisbeeinträchtigung" },
      { name: "Konfabulations-Screening", score: "Positiv (spontan + provoziert)", norm: "Negativ", interpretation: "Ausgeprägte Konfabulation" },
    ],
    conclusion: "Vollbild Korsakoff-Syndrom. Schwere anterograde Amnesie, signifikante retrograde Amnesie, Konfabulation. Alltagskompetenz erheblich eingeschränkt — betreutes Wohnen / Heimversorgung notwendig.",
  },
];

Object.assign(window, {
  PATIENTS, OP_ROOMS, OP_PROCEDURES, ICU_VITALS, ICU_PATIENTS_EXTRA,
  MEDICATION, LAB_RESULTS, STATIONS, IMAGING, AGENDA, TASKS, REFERRALS,
  SOAP_HISTORY, NEURO_PSYCH,
});
