/* Mock clinical data — Medion KIS */

const PATIENTS = [
  {
    id: "P-104821",
    name: "Müller, Hannelore",
    geb: "14.03.1948",
    age: 78,
    sex: "w",
    insurance: { type: "GKV", name: "AOK Bayern", number: "A123456789", egk: true },
    station: "INT-3", room: "312", bed: "B",
    admit: "23.04.2026 07:42",
    los: 2,
    primary: "I50.13 — Herzinsuffizienz, NYHA III",
    secondary: ["E11.9 — Diabetes mellitus Typ 2", "I10.90 — Hypertonie"],
    allergies: ["Penicillin (anaphylaktisch)", "Kontrastmittel iod."],
    attending: "Dr. Weber",
    nurse: "Schwester Linda",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Notfall",
    vitals: { hr: 78, sys: 132, dia: 84, spo2: 96, temp: 37.1, rr: 16 },
  },
  {
    id: "P-104822",
    name: "Schmidt, Klaus-Dieter",
    geb: "02.11.1959",
    age: 66,
    sex: "m",
    insurance: { type: "GKV", name: "Techniker Krankenkasse", number: "T998123456", egk: true },
    station: "CHIR-2", room: "207", bed: "A",
    admit: "22.04.2026 14:10",
    los: 3,
    primary: "K35.30 — Akute Appendizitis mit Peritonitis",
    secondary: ["I10.90 — Hypertonie"],
    allergies: ["Keine bekannt"],
    attending: "Dr. Bauer",
    nurse: "Pfleger Tobias",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Notfall — OP",
    vitals: { hr: 82, sys: 128, dia: 78, spo2: 98, temp: 36.9, rr: 14 },
  },
  {
    id: "P-104823",
    name: "Yılmaz, Ayşe",
    geb: "27.07.1972",
    age: 53,
    sex: "w",
    insurance: { type: "GKV", name: "BARMER", number: "B554210019", egk: true },
    station: "ITS", room: "I-04", bed: "—",
    admit: "21.04.2026 22:55",
    los: 4,
    primary: "J96.00 — Akute respiratorische Insuffizienz",
    secondary: ["U07.1 — COVID-19, Virus nachgewiesen", "E66.99 — Adipositas"],
    allergies: ["Latex"],
    attending: "Dr. Hofmann",
    nurse: "Schwester Marta",
    severity: "critical",
    dnr: false,
    aufnahmeart: "Verlegung extern",
    vitals: { hr: 112, sys: 96, dia: 58, spo2: 89, temp: 38.7, rr: 26 },
  },
  {
    id: "P-104824",
    name: "Becker, Liam",
    geb: "08.09.2017",
    age: 8,
    sex: "m",
    insurance: { type: "GKV", name: "DAK-Gesundheit", number: "D201730018", egk: true },
    station: "PÄD", room: "104", bed: "C",
    admit: "24.04.2026 09:15",
    los: 1,
    primary: "S52.5 — Distale Radiusfraktur rechts",
    secondary: [],
    allergies: ["Erdnüsse"],
    attending: "Dr. Köhler",
    nurse: "Schwester Bea",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Elektiv",
    vitals: { hr: 92, sys: 106, dia: 64, spo2: 99, temp: 36.7, rr: 18 },
  },
  {
    id: "P-104825",
    name: "Nowak, Stefan",
    geb: "19.05.1981",
    age: 44,
    sex: "m",
    insurance: { type: "PKV", name: "DKV Premium", number: "PKV-883201", egk: false },
    station: "CHIR-1", room: "118", bed: "A",
    admit: "24.04.2026 06:30",
    los: 1,
    primary: "M23.21 — Meniskusriss medial, Kniegelenk links",
    secondary: [],
    allergies: ["Keine bekannt"],
    attending: "Dr. Bauer",
    nurse: "Pfleger Tobias",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Elektiv — OP heute",
    vitals: { hr: 70, sys: 124, dia: 78, spo2: 99, temp: 36.6, rr: 14 },
  },
  {
    id: "P-104826",
    name: "Fischer, Renate",
    geb: "30.01.1942",
    age: 84,
    sex: "w",
    insurance: { type: "GKV", name: "AOK Plus", number: "A772091833", egk: true },
    station: "INT-3", room: "315", bed: "A",
    admit: "20.04.2026 11:20",
    los: 5,
    primary: "I63.9 — Hirninfarkt, nicht näher bezeichnet",
    secondary: ["I48.0 — Vorhofflimmern", "F03 — Demenz, n.n.b."],
    allergies: ["ASS"],
    attending: "Dr. Weber",
    nurse: "Schwester Linda",
    severity: "watch",
    dnr: true,
    aufnahmeart: "Notfall",
    vitals: { hr: 88, sys: 148, dia: 92, spo2: 95, temp: 37.4, rr: 18 },
  },
  {
    id: "P-104827",
    name: "Krause, Mehmet",
    geb: "12.06.1968",
    age: 57,
    sex: "m",
    insurance: { type: "GKV", name: "AOK Bayern", number: "A331092118", egk: true },
    station: "INT-3", room: "318", bed: "B",
    admit: "23.04.2026 19:05",
    los: 2,
    primary: "K70.30 — Alkoholische Leberzirrhose",
    secondary: ["F10.2 — Alkoholabhängigkeit"],
    allergies: ["Keine bekannt"],
    attending: "Dr. Weber",
    nurse: "Schwester Linda",
    severity: "watch",
    dnr: false,
    aufnahmeart: "Notfall",
    vitals: { hr: 102, sys: 104, dia: 62, spo2: 94, temp: 37.8, rr: 20 },
  },
  {
    id: "P-104828",
    name: "Vogel, Petra",
    geb: "09.10.1989",
    age: 36,
    sex: "w",
    insurance: { type: "GKV", name: "Techniker Krankenkasse", number: "T771820019", egk: true },
    station: "GYN", room: "402", bed: "B",
    admit: "24.04.2026 02:18",
    los: 1,
    primary: "O80 — Spontangeburt eines Einlings",
    secondary: ["Z37.0 — Lebendgeborenes Einling"],
    allergies: ["Keine bekannt"],
    attending: "Dr. Lange",
    nurse: "Hebamme Anja",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Geburt",
    vitals: { hr: 76, sys: 118, dia: 72, spo2: 99, temp: 36.8, rr: 14 },
  },
  {
    id: "P-104829",
    name: "Hartmann, Ingo",
    geb: "21.04.1955",
    age: 71,
    sex: "m",
    insurance: { type: "GKV", name: "BARMER", number: "B118208329", egk: true },
    station: "ITS", room: "I-02", bed: "—",
    admit: "22.04.2026 04:50",
    los: 3,
    primary: "I21.4 — NSTEMI",
    secondary: ["I25.13 — KHK", "E78.0 — Hypercholesterinämie"],
    allergies: ["Keine bekannt"],
    attending: "Dr. Hofmann",
    nurse: "Schwester Marta",
    severity: "watch",
    dnr: false,
    aufnahmeart: "Notfall — Herzkatheter",
    vitals: { hr: 64, sys: 118, dia: 70, spo2: 97, temp: 36.8, rr: 16 },
  },
  {
    id: "P-104830",
    name: "Roth, Sabine",
    geb: "05.12.1976",
    age: 49,
    sex: "w",
    insurance: { type: "GKV", name: "DAK-Gesundheit", number: "D661920401", egk: true },
    station: "CHIR-2", room: "211", bed: "A",
    admit: "24.04.2026 08:40",
    los: 1,
    primary: "K80.20 — Cholezystolithiasis",
    secondary: [],
    allergies: ["Morphin"],
    attending: "Dr. Bauer",
    nurse: "Pfleger Tobias",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Elektiv — OP heute",
    vitals: { hr: 74, sys: 126, dia: 80, spo2: 98, temp: 36.7, rr: 14 },
  },
  {
    id: "P-104831",
    name: "Kaiser, Otto",
    geb: "11.02.1939",
    age: 87,
    sex: "m",
    insurance: { type: "GKV", name: "AOK Plus", number: "A992101188", egk: true },
    station: "INT-3", room: "320", bed: "A",
    admit: "19.04.2026 23:10",
    los: 6,
    primary: "J18.9 — Pneumonie, n.n.b.",
    secondary: ["F03 — Demenz", "Z74.1 — Hilfsbedürftigkeit Pflege"],
    allergies: ["Penicillin"],
    attending: "Dr. Weber",
    nurse: "Schwester Linda",
    severity: "stable",
    dnr: true,
    aufnahmeart: "Notfall",
    vitals: { hr: 84, sys: 122, dia: 76, spo2: 96, temp: 37.5, rr: 18 },
  },
  {
    id: "P-104832",
    name: "Schneider, Anna",
    geb: "23.08.1995",
    age: 30,
    sex: "w",
    insurance: { type: "GKV", name: "Techniker Krankenkasse", number: "T420118229", egk: true },
    station: "GYN", room: "405", bed: "A",
    admit: "23.04.2026 17:30",
    los: 2,
    primary: "N80.9 — Endometriose",
    secondary: [],
    allergies: ["Keine bekannt"],
    attending: "Dr. Lange",
    nurse: "Hebamme Anja",
    severity: "stable",
    dnr: false,
    aufnahmeart: "Elektiv",
    vitals: { hr: 72, sys: 116, dia: 70, spo2: 99, temp: 36.6, rr: 14 },
  },
];

// OR / OP-Plan
const OP_ROOMS = ["OP-1", "OP-2", "OP-3", "OP-4 (Notfall)"];
const OP_PROCEDURES = [
  { id: "OP-2401", room: "OP-1", patient: "P-104825", patientName: "Nowak, S.", procedure: "Arthroskopie Knie li. — Meniskusresektion", surgeon: "Dr. Bauer", anaesthetist: "Dr. Schulz", start: "08:00", end: "09:30", status: "completed", priority: "elektiv" },
  { id: "OP-2402", room: "OP-1", patient: "P-104830", patientName: "Roth, S.", procedure: "Lap. Cholezystektomie", surgeon: "Dr. Bauer", anaesthetist: "Dr. Schulz", start: "10:00", end: "11:45", status: "in-progress", priority: "elektiv" },
  { id: "OP-2403", room: "OP-1", patient: "P-104840", patientName: "Wagner, M.", procedure: "Hernia inguinalis re., TEP", surgeon: "Dr. Bauer", anaesthetist: "Dr. Schulz", start: "12:30", end: "13:45", status: "scheduled", priority: "elektiv" },
  { id: "OP-2404", room: "OP-1", patient: "P-104841", patientName: "Decker, R.", procedure: "Strumaresektion subtotal", surgeon: "Dr. Bauer", anaesthetist: "Dr. Schulz", start: "14:30", end: "16:30", status: "scheduled", priority: "elektiv" },

  { id: "OP-2410", room: "OP-2", patient: "P-104842", patientName: "Brandt, U.", procedure: "Hüft-TEP rechts", surgeon: "Dr. Engel", anaesthetist: "Dr. Pohl", start: "07:30", end: "10:30", status: "completed", priority: "elektiv" },
  { id: "OP-2411", room: "OP-2", patient: "P-104843", patientName: "Lehmann, F.", procedure: "Knie-TEP links", surgeon: "Dr. Engel", anaesthetist: "Dr. Pohl", start: "11:00", end: "13:30", status: "in-progress", priority: "elektiv" },
  { id: "OP-2412", room: "OP-2", patient: "P-104844", patientName: "Hess, T.", procedure: "Schulterarthroskopie", surgeon: "Dr. Engel", anaesthetist: "Dr. Pohl", start: "14:30", end: "16:00", status: "scheduled", priority: "elektiv" },

  { id: "OP-2420", room: "OP-3", patient: "P-104845", patientName: "Klein, P.", procedure: "Sectio caesarea", surgeon: "Dr. Lange", anaesthetist: "Dr. Pohl", start: "09:00", end: "10:00", status: "completed", priority: "elektiv" },
  { id: "OP-2421", room: "OP-3", patient: "P-104846", patientName: "Otto, B.", procedure: "Hysterektomie laparoskopisch", surgeon: "Dr. Lange", anaesthetist: "Dr. Mayer", start: "11:00", end: "13:30", status: "scheduled", priority: "elektiv" },
  { id: "OP-2422", room: "OP-3", patient: "P-104847", patientName: "Reinhardt, K.", procedure: "Konisation", surgeon: "Dr. Lange", anaesthetist: "Dr. Mayer", start: "14:30", end: "15:15", status: "scheduled", priority: "elektiv" },

  { id: "OP-2430", room: "OP-4 (Notfall)", patient: "P-104822", patientName: "Schmidt, K.-D.", procedure: "Appendektomie laparoskopisch", surgeon: "Dr. Bauer", anaesthetist: "Dr. Schulz", start: "01:15", end: "02:30", status: "completed", priority: "notfall" },
  { id: "OP-2431", room: "OP-4 (Notfall)", patient: "P-104848", patientName: "Köhler, J.", procedure: "Re-Laparotomie — Nachblutung", surgeon: "Dr. Engel", anaesthetist: "Dr. Pohl", start: "13:00", end: "—", status: "scheduled", priority: "notfall" },
];

// ICU vitals over time (sparkline data)
const ICU_VITALS = {
  "P-104823": {
    hr:   [108, 112, 110, 115, 118, 114, 112, 110, 108, 112, 116, 112],
    sys:  [102, 100,  98,  96,  94,  96,  98,  96,  94,  92,  94,  96],
    spo2: [ 92,  91,  90,  89,  88,  87,  88,  89,  88,  88,  89,  89],
    rr:   [ 22,  24,  26,  28,  26,  24,  26,  26,  28,  26,  26,  26],
  },
  "P-104829": {
    hr:   [ 60,  62,  64,  66,  64,  62,  60,  62,  64,  66,  64,  64],
    sys:  [120, 122, 118, 116, 118, 120, 122, 118, 116, 118, 120, 118],
    spo2: [ 98,  98,  97,  97,  98,  98,  97,  97,  98,  97,  97,  97],
    rr:   [ 14,  16,  16,  18,  16,  16,  14,  16,  16,  18,  16,  16],
  },
  "P-104852": {
    hr:   [ 96,  98,  94,  92,  94,  96,  98,  96,  94,  96,  98,  96],
    sys:  [108, 110, 112, 110, 108, 106, 108, 110, 112, 108, 110, 108],
    spo2: [ 94,  93,  94,  95,  94,  93,  94,  94,  93,  94,  94,  94],
    rr:   [ 20,  22,  20,  18,  20,  22,  20,  20,  22,  20,  20,  20],
  },
};

const ICU_PATIENTS_EXTRA = [
  {
    id: "P-104852",
    name: "Albrecht, Werner",
    geb: "06.07.1953",
    age: 72,
    sex: "m",
    station: "ITS", room: "I-06", bed: "—",
    primary: "T82.7 — Sepsis nach Klappenersatz",
    severity: "watch",
    vitals: { hr: 96, sys: 108, dia: 64, spo2: 94, temp: 38.2, rr: 20 },
    ventilator: { mode: "PSV", peep: 8, fio2: 0.45, vt: 480, rr: 18 },
    sedation: "RASS -1",
    drugs: ["Noradrenalin 0.08 µg/kg/min", "Propofol 200 mg/h", "Meropenem 1 g 8h"],
    catheters: ["ZVK", "Arterie", "DK", "ZVD"],
  },
];

const MEDICATION = [
  // For Müller, Hannelore (P-104821)
  { patient: "P-104821", name: "Bisoprolol 5 mg", form: "Tabl.", route: "p.o.", schedule: "1-0-0", times: ["08:00"], from: "23.04.", until: "—", indication: "Herzinsuffizienz", interaction: false, aut: false, status: "ok" },
  { patient: "P-104821", name: "Ramipril 5 mg", form: "Tabl.", route: "p.o.", schedule: "1-0-1", times: ["08:00", "20:00"], from: "23.04.", until: "—", indication: "Hypertonie / HI", interaction: false, aut: false, status: "ok" },
  { patient: "P-104821", name: "Furosemid 40 mg", form: "Tabl.", route: "p.o.", schedule: "1-0-0", times: ["08:00"], from: "23.04.", until: "—", indication: "Volumenüberladung", interaction: false, aut: false, status: "ok" },
  { patient: "P-104821", name: "Metformin 1000 mg", form: "Tabl.", route: "p.o.", schedule: "1-0-1", times: ["08:00", "20:00"], from: "23.04.", until: "—", indication: "DM Typ 2", interaction: false, aut: true, status: "ok" },
  { patient: "P-104821", name: "Atorvastatin 40 mg", form: "Tabl.", route: "p.o.", schedule: "0-0-1", times: ["20:00"], from: "23.04.", until: "—", indication: "Lipidsenkung", interaction: false, aut: true, status: "ok" },
  { patient: "P-104821", name: "Apixaban 5 mg", form: "Tabl.", route: "p.o.", schedule: "1-0-1", times: ["08:00", "20:00"], from: "23.04.", until: "—", indication: "Antikoagulation", interaction: true, aut: false, status: "warn", warning: "Wechselwirkung mit Amiodaron — INR überwachen" },
  { patient: "P-104821", name: "Pantoprazol 40 mg", form: "Tabl.", route: "p.o.", schedule: "1-0-0", times: ["08:00"], from: "23.04.", until: "—", indication: "Magenschutz", interaction: false, aut: false, status: "ok" },
];

const LAB_RESULTS = [
  { patient: "P-104821", date: "24.04. 06:14", panel: "Klinische Chemie", values: [
    { name: "Kreatinin", v: "1.42", unit: "mg/dl", ref: "0.5–1.1", flag: "high" },
    { name: "Harnstoff", v: "62", unit: "mg/dl", ref: "10–50", flag: "high" },
    { name: "GFR (CKD-EPI)", v: "44", unit: "ml/min", ref: ">60", flag: "low" },
    { name: "Natrium", v: "138", unit: "mmol/l", ref: "135–145", flag: "ok" },
    { name: "Kalium", v: "4.2", unit: "mmol/l", ref: "3.5–5.0", flag: "ok" },
    { name: "NT-proBNP", v: "3 240", unit: "pg/ml", ref: "<300", flag: "high" },
    { name: "Troponin T hs", v: "18", unit: "ng/l", ref: "<14", flag: "high" },
    { name: "CRP", v: "8.4", unit: "mg/l", ref: "<5", flag: "high" },
  ]},
  { patient: "P-104821", date: "24.04. 06:14", panel: "Hämatologie", values: [
    { name: "Hb", v: "11.2", unit: "g/dl", ref: "12.0–16.0", flag: "low" },
    { name: "Leukozyten", v: "8.4", unit: "/nl", ref: "4.0–10.0", flag: "ok" },
    { name: "Thrombozyten", v: "212", unit: "/nl", ref: "150–400", flag: "ok" },
  ]},
];

// Stations / wards
const STATIONS = [
  { code: "INT-3", name: "Innere Medizin 3 — Kardiologie", beds: 28, occupied: 24, free: 4, isolation: 1, lead: "Dr. Weber", floor: "3. OG" },
  { code: "INT-4", name: "Innere Medizin 4 — Pneumologie", beds: 24, occupied: 22, free: 2, isolation: 3, lead: "Dr. Sommer", floor: "3. OG" },
  { code: "CHIR-1", name: "Allgemein- & Viszeralchirurgie", beds: 30, occupied: 26, free: 4, isolation: 0, lead: "Dr. Bauer", floor: "2. OG" },
  { code: "CHIR-2", name: "Unfallchirurgie & Orthopädie", beds: 26, occupied: 23, free: 3, isolation: 0, lead: "Dr. Engel", floor: "2. OG" },
  { code: "ITS", name: "Intensivstation", beds: 12, occupied: 10, free: 2, isolation: 4, lead: "Dr. Hofmann", floor: "1. OG" },
  { code: "GYN", name: "Gynäkologie & Geburtshilfe", beds: 22, occupied: 18, free: 4, isolation: 0, lead: "Dr. Lange", floor: "4. OG" },
  { code: "PÄD", name: "Pädiatrie", beds: 20, occupied: 14, free: 6, isolation: 1, lead: "Dr. Köhler", floor: "4. OG" },
  { code: "NEU", name: "Neurologie / Stroke Unit", beds: 18, occupied: 16, free: 2, isolation: 0, lead: "Dr. Richter", floor: "5. OG" },
];

// Imaging studies
const IMAGING = [
  { id: "S-44021", patient: "P-104821", date: "24.04.2026 07:55", modality: "Rö-Thorax", region: "Thorax pa/lateral", status: "befundet", radiologist: "Dr. Wolff", indication: "Dyspnoe, V.a. kardiale Stauung", findings: "Vergrößertes Herz (CTR 0.62), interstitielle Stauungszeichen, beidseits basal kleine Pleuraergüsse. Keine pneumonische Infiltration." },
  { id: "S-44022", patient: "P-104826", date: "20.04.2026 12:45", modality: "MRT", region: "Schädel nativ + KM", status: "befundet", radiologist: "Dr. Wolff", indication: "V.a. Hirninfarkt", findings: "Frischer ischämischer Infarkt im Mediastromgebiet rechts (DWI+, ADC↓). Keine Blutung." },
  { id: "S-44023", patient: "P-104823", date: "23.04.2026 02:30", modality: "CT", region: "Thorax + KM", status: "befundet", radiologist: "Dr. Bach", indication: "ARDS, V.a. Lungenembolie", findings: "Ausgedehnte beidseitige Milchglas-Trübungen, betont posterior. Keine zentrale Lungenembolie. Pleuraergüsse rechts > links." },
  { id: "S-44024", patient: "P-104822", date: "22.04.2026 13:20", modality: "Sonographie", region: "Abdomen", status: "befundet", radiologist: "Dr. Bach", indication: "RUQ-Schmerz, V.a. Appendizitis", findings: "Wandverdickte, nicht komprimierbare Appendix, Durchmesser 11 mm. Freie Flüssigkeit periappendikulär." },
  { id: "S-44025", patient: "P-104829", date: "22.04.2026 06:10", modality: "Koro", region: "Linksherzkatheter", status: "befundet", radiologist: "Dr. Wolff", indication: "NSTEMI", findings: "Hochgradige Stenose RIVA prox. (90%). PCI mit DES erfolgreich. RCA und RCX o.B." },
];

// Today's appointments / agenda
const AGENDA = [
  { time: "07:30", title: "Morgenvisite Station INT-3", duration: "60 min", type: "visite", location: "Station 3", attendees: 4 },
  { time: "09:00", title: "Tumorboard — Wöchentlich", duration: "45 min", type: "konferenz", location: "Konferenzraum B", attendees: 12 },
  { time: "10:00", title: "Aufklärung OP — Frau Roth", duration: "20 min", type: "aufklärung", location: "Zimmer 211", attendees: 1, patient: "Roth, Sabine" },
  { time: "10:30", title: "Sprechstunde — Müller, Hannelore", duration: "15 min", type: "termin", location: "Zimmer 312", attendees: 1, patient: "Müller, Hannelore" },
  { time: "11:00", title: "Konsil Neurologie — Hr. Krause", duration: "30 min", type: "konsil", location: "INT-3", attendees: 2, patient: "Krause, Mehmet" },
  { time: "13:00", title: "Mittagsbesprechung", duration: "30 min", type: "team", location: "Arztzimmer", attendees: 8 },
  { time: "14:30", title: "Entlassgespräch — Hr. Becker", duration: "20 min", type: "entlassung", location: "PÄD 104", attendees: 2, patient: "Becker, Liam" },
  { time: "16:00", title: "Abendvisite", duration: "45 min", type: "visite", location: "Station 3", attendees: 3 },
];

// Tasks / inbox
const TASKS = [
  { id: 1, prio: "high", text: "Befund freigeben: CT-Thorax — Yılmaz, A.", from: "Dr. Bach", time: "vor 12 Min.", type: "befund" },
  { id: 2, prio: "high", text: "Rückruf Angehörige Frau Fischer", from: "Stationssekretariat", time: "vor 38 Min.", type: "telefonat" },
  { id: 3, prio: "med", text: "eAU verlängern — Hr. Krause", from: "MFA Stark", time: "vor 1 Std.", type: "eau" },
  { id: 4, prio: "med", text: "Antrag AHB — Frau Müller", from: "Sozialdienst", time: "vor 1 Std.", type: "antrag" },
  { id: 5, prio: "med", text: "Konsil Kardiologie offen — Hr. Hartmann", from: "Dr. Sommer", time: "vor 2 Std.", type: "konsil" },
  { id: 6, prio: "low", text: "Arztbrief gegenzeichnen — 4 Briefe", from: "System", time: "vor 3 Std.", type: "brief" },
  { id: 7, prio: "low", text: "Pflegeüberleitung Hr. Kaiser", from: "Pflege INT-3", time: "vor 4 Std.", type: "ueberleitung" },
];

const REFERRALS = [
  { id: "Ü-2026-0241", date: "23.04.2026", patient: "Müller, Hannelore", to: "Kardiologie ambulant — Praxis Dr. Berger", reason: "TTE, Verlaufskontrolle Herzinsuffizienz", urgency: "regulär", status: "versendet" },
  { id: "Ü-2026-0242", date: "23.04.2026", patient: "Krause, Mehmet", to: "Suchtmedizin — MVZ Süd", reason: "Anschlussbehandlung Alkoholentzug", urgency: "regulär", status: "Entwurf" },
  { id: "Ü-2026-0243", date: "24.04.2026", patient: "Becker, Liam", to: "Physiotherapie — Praxis Lehner", reason: "Mobilisation nach Radiusfraktur", urgency: "regulär", status: "versendet" },
  { id: "Ü-2026-0244", date: "24.04.2026", patient: "Fischer, Renate", to: "Geriatrische Reha — Klinik Sonnenhof", reason: "AHB nach Hirninfarkt", urgency: "hoch", status: "in Bearbeitung" },
];

Object.assign(window, {
  PATIENTS, OP_ROOMS, OP_PROCEDURES, ICU_VITALS, ICU_PATIENTS_EXTRA,
  MEDICATION, LAB_RESULTS, STATIONS, IMAGING, AGENDA, TASKS, REFERRALS,
});
